resolver: lts-6.23

packages:
- '.'
- './coloured-petri-nets-act'
# - location:
#     git: git@github.com:azardilis/coloured-petri-nets.git
#     commit: 2e39c0449cd3ec6b37ebda24eab73ea3a765388e
#   extra-dep: true
  
extra-deps: [normaldistribution-1.1.0.3]
